### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by mgattozzi**
When coming to a project sometimes people need to file issues! With different types of issues though different kinds of information is warranted to solve it. Sometimes it's not even an issue but a feature request! This commit adds some issue templates to make it easy for people to file what information we the maintainers need to make better docs.

cc/ @rustwasm/book 
I'd like to hear more of your opinions before we merge this. Should we add more types of issue templates? Do these need to be improved?

### CODE REVIEW

**Comment by fitzgen** [comment]
I've never seen multiple issue template before -- how does github present these?

**Comment by mgattozzi** [comment]
A good example would be [parceljs found here](https://github.com/parcel-bundler/parcel/issues/new/choose) to see how they get represented!

**Comment by mgattozzi** [comment]
I think this now encompasses #31 that @sarahmeyer filed today!

**Comment by mgattozzi** [comment]
Totally fine! Thanks for merging @fitzgen

**Pull request merged**
