### PR TITLE
List prerequisites for game-of-life tutorial.

### PR DESCRIPTION
**Pull request by pchickey**
**Summary**

I hadn't heard of `cargo-generate` before this tutorial so this tripped me up as I went through it. I added a section at the start of the tutorial to indicate that rustup, wasm-pack, and cargo-generate all need to be installed before starting.

* [ ] 👯 This PR is not a duplicate
* [ ] 📬 This PR addresses an open issue
* [ ] ✅ This PR has passed CI

### CODE REVIEW

**Comment by fitzgen** [comment]
These prerequisites are all listed in the "setup" chapter, which is the very first chapter of the tutorial: https://rustwasm.github.io/book/game-of-life/setup.html

I don't really want to duplicate this info and have to maintain two copies. Do you think it would be useful to instead add a blurb about "make sure you installed the prequisites listed in the setup chapter before continuing" to the top of this chapter?

**Comment by pchickey** [comment]
oh! I'm sorry, I never even saw that chapter as I went through this tutorial. Yes, I think it would be useful to have that as a single sentence at the top of the tutorial, rather than duplicate the information. I'll change this PR to do that instead.

**Comment by fitzgen** [comment]
Cool, let me know when you've updated the PR :)

**Comment by pchickey** [comment]
I have replaced the previous commit with a new one

**Pull request merged**
